/**
 * Class inventory for scripts/prerender.mjs public shell.
 * Kept in src so Tailwind v4 includes these utilities in the production CSS bundle.
 * Keep in sync with renderBody() in scripts/prerender.mjs.
 */
export const PRERENDER_SHELL_CLASS_INVENTORY = [
  'text-slate-500',
  'flex min-h-screen flex-col bg-white',
  'sticky top-0 z-[100] w-full border-b border-slate-100 bg-white',
  'mx-auto flex h-16 max-w-7xl items-center justify-between gap-4 px-4 sm:px-6 lg:px-8',
  'flex shrink-0 items-center gap-2',
  'flex shrink-0 items-center',
  'block shrink-0 object-contain object-left',
  'text-lg font-semibold tracking-tight text-slate-900',
  'hidden min-w-0 flex-1 items-center justify-center gap-1 lg:flex',
  'whitespace-nowrap rounded-lg px-2.5 py-1.5 text-sm font-medium text-slate-700 hover:text-slate-900',
  'flex flex-wrap items-center justify-center gap-1 px-4 py-2 lg:hidden',
  'flex-1',
  'relative w-full overflow-hidden bg-slate-900',
  'relative w-full overflow-hidden bg-slate-900 aspect-[3/1] max-[640px]:aspect-[9/16]',
  'relative w-full overflow-hidden bg-gradient-to-br from-slate-900 via-slate-800 to-green-900 aspect-[3/1] max-[640px]:aspect-[9/16]',
  'pointer-events-none absolute inset-0 z-[2]',
  'mx-auto flex h-full w-full max-w-7xl flex-col justify-center px-4 py-8 text-white sm:py-16',
  'absolute inset-0 h-full w-full object-contain object-center',
  'mb-4 text-3xl font-semibold leading-tight text-white drop-shadow md:text-4xl lg:text-5xl',
  'mb-6 max-w-xl text-base leading-relaxed text-gray-300 drop-shadow md:text-lg',
  'relative overflow-hidden bg-gradient-to-br from-slate-900 via-slate-800 to-green-900 py-12 sm:py-16 lg:py-20',
  'relative overflow-hidden bg-gradient-to-br from-slate-950 via-slate-900 to-emerald-950 py-12 md:py-16 lg:py-20',
  'absolute inset-0 bg-[radial-gradient(circle_at_30%_50%,rgba(34,197,94,0.2),transparent_70%)]',
  'pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_20%_40%,rgba(34,197,94,0.15),transparent_55%)]',
  'relative z-10 mx-auto max-w-7xl px-4 sm:px-6 lg:px-8',
  'grid max-w-3xl items-center gap-10 lg:gap-12',
  'grid max-w-4xl items-center gap-10 lg:gap-16',
  'text-white',
  'mb-4 inline-block rounded-full bg-green-500/20 px-3 py-1.5',
  'text-xs font-medium text-green-400',
  'mb-4 inline-flex items-center rounded-full border border-emerald-500/30 bg-emerald-500/10 px-3 py-1.5 text-xs font-semibold uppercase tracking-wide text-emerald-400',
  'mb-4 text-3xl font-semibold leading-tight text-white md:text-4xl lg:text-5xl',
  'text-3xl font-bold leading-tight tracking-tight text-white md:text-4xl lg:text-5xl',
  'mb-6 max-w-xl text-base leading-relaxed text-gray-300 md:text-lg',
  'mt-5 max-w-xl text-base leading-relaxed text-slate-300 md:text-lg',
  'mb-5 flex flex-wrap gap-2 text-sm text-slate-300',
  'text-slate-400 hover:text-white',
  'text-slate-200',
  'flex flex-wrap gap-3',
  'inline-flex items-center justify-center gap-2 rounded-lg bg-green-600 px-6 py-2.5 text-sm font-medium text-white',
  'inline-flex items-center justify-center rounded-lg border border-white/30 px-6 py-2.5 text-sm font-medium text-white',
  'border-b border-slate-200 bg-slate-50 py-10',
  'text-sm font-semibold uppercase tracking-wide text-slate-500',
  'mt-5 grid gap-4 sm:grid-cols-3',
  'mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4',
  'block rounded-2xl border border-slate-200 bg-white p-5',
  'text-base font-semibold text-slate-900',
  'mt-2 text-sm leading-relaxed text-slate-600',
  'mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8',
  'max-w-3xl text-base leading-relaxed text-slate-600',
  'mt-4 space-y-2 text-sm text-slate-600',
  'font-medium text-emerald-700 hover:text-emerald-800',
  'border-t border-slate-200 bg-slate-900 text-slate-300',
  'mx-auto max-w-7xl px-4 py-12 sm:px-6',
  'grid gap-10 sm:grid-cols-2 lg:grid-cols-4',
  'sm:col-span-2 lg:col-span-1',
  'text-lg font-semibold text-white',
  'mt-3 text-sm leading-relaxed text-slate-400',
  'mt-5 flex flex-wrap items-center gap-2',
  'inline-flex h-10 items-center justify-center rounded-lg border border-slate-700 px-3 text-xs font-medium text-slate-300',
  'mt-10 flex flex-col gap-2 border-t border-slate-800 pt-6 text-xs text-slate-500 sm:flex-row sm:items-center sm:justify-between',
].join(' ')
